default: &default
  adapter: postgresql
  encoding: unicode
  database: "<%= ENV.fetch("POSTGRES_DB") { "typerek" } %>"
  username: "<%= ENV.fetch("POSTGRES_USER") { "postgres" } %>"
  password: "<%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>"
  host: "<%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>"
  port: "<%= ENV.fetch("POSTGRES_PORT") { 5432 } %>"
  pool: "<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>"

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "typerek" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "typerek" } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "typerek" } %>_production
