# -*- encoding : utf-8 -*-
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)

User.create(:username => "admin", :password => "password", :password_confirmation => "password")
User.last.update_attribute(:admin, true)

Round.create(:name => '1')
Match.create(:teamA => 'Lech Poznań', :teamB => 'Piast Gliwice', :start => '2014-07-20 15:30', :round_id => Round.last.id, :resultA => 4, :resultB => 0)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'GKS Bełchatów', :start => '2014-07-19 20:30', :round_id => Round.last.id, :resultA => 0, :resultB => 1)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Cracovia', :start => '2014-07-21 18:00', :round_id => Round.last.id, :resultA => 2, :resultB => 0)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Lechia Gdańsk', :start => '2014-07-19 18:00', :round_id => Round.last.id, :resultA => 2, :resultB => 2)
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Korona Kielce', :start => '2014-07-20 15:30', :round_id => Round.last.id, :resultA => 2, :resultB => 0)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Ruch Chorzów', :start => '2014-07-20 18:00', :round_id => Round.last.id, :resultA => 2, :resultB => 0)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Pogoń Szczecin', :start => '2014-07-18 18:00', :round_id => Round.last.id, :resultA => 2, :resultB => 3)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Wisła Kraków', :start => '2014-07-18 20:30', :round_id => Round.last.id, :resultA => 1, :resultB => 1)
Round.create(:name => '2')
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Piast Gliwice', :start => '2014-07-28 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Lech Poznań', :start => '2014-07-27 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2014-07-25 20:30', :round_id => Round.last.id)
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Górnik Łęczna', :start => '2014-07-27 15:30', :round_id => Round.last.id)
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Śląsk Wrocław', :start => '2014-07-26 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Korona Kielce', :start => '2014-07-25 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Jagiellonia Białystok', :start => '2014-07-27 15:30', :round_id => Round.last.id)
Match.create(:teamA => 'Cracovia', :teamB => 'Legia Warszawa', :start => '2014-07-26 20:30', :round_id => Round.last.id)
Round.create(:name => '3')
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Lechia Gdańsk', :start => '2014-08-1 20:30', :round_id => Round.last.id)
Match.create(:teamA => 'Lech Poznań', :teamB => 'Wisła Kraków', :start => '2014-08-3 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Górnik Zabrze', :start => '2014-08-2 20:30', :round_id => Round.last.id)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Cracovia', :start => '2014-08-1 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Pogoń Szczecin', :start => '2014-08-2 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Zawisza Bydgoszcz', :start => '2014-08-3 15:30', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Ruch Chorzów', :start => '2014-08-3 15:30', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'GKS Bełchatów', :start => '2014-08-4 18:00', :round_id => Round.last.id)
Round.create(:name => '4')
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Lech Poznań', :start => '2014-08-10 15:30', :round_id => Round.last.id)
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Wisła Kraków', :start => '2014-08-10 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Piast Gliwice', :start => '2014-08-11 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Śląsk Wrocław', :start => '2014-08-8 20:30', :round_id => Round.last.id)
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2014-08-10 15:30', :round_id => Round.last.id)
Match.create(:teamA => 'Cracovia', :teamB => 'Korona Kielce', :start => '2014-08-8 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Górnik Łęczna', :start => '2014-08-9 20:30', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Jagiellonia Białystok', :start => '2014-08-9 18:00', :round_id => Round.last.id)
Round.create(:name => '5')
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Ruch Chorzów', :start => '2014-08-16 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Lechia Gdańsk', :start => '2014-08-17 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Lech Poznań', :teamB => 'Pogoń Szczecin', :start => '2014-08-16 20:30', :round_id => Round.last.id)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Legia Warszawa', :start => '2014-08-15 20:30', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Górnik Zabrze', :start => '2014-08-15 18:30', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Cracovia', :start => '2014-08-17 15:30', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'GKS Bełchatów', :start => '2014-08-18 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Zawisza Bydgoszcz', :start => '2014-08-16 15:30', :round_id => Round.last.id)
Round.create(:name => '6')
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Lech Poznań', :start => '2014-08-24 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Wisła Kraków', :start => '2014-08-22 20:30', :round_id => Round.last.id)
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Piast Gliwice', :start => '2014-08-25 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Lechia Gdańsk', :start => '2014-08-22 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Cracovia', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2014-08-23 15:30', :round_id => Round.last.id)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Korona Kielce', :start => '2014-08-23 20:30', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Górnik Łęczna', :start => '2014-08-23 18:00', :round_id => Round.last.id)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Śląsk Wrocław', :start => '2014-08-24 15:30', :round_id => Round.last.id)
Round.create(:name => '7')
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Zawisza Bydgoszcz', :start => '2014-08-30', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'GKS Bełchatów', :start => '2014-08-30', :round_id => Round.last.id)
Match.create(:teamA => 'Lech Poznań', :teamB => 'Cracovia', :start => '2014-08-30', :round_id => Round.last.id)
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Ruch Chorzów', :start => '2014-08-30', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Jagiellonia Białystok', :start => '2014-08-30', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Górnik Zabrze', :start => '2014-08-30', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Legia Warszawa', :start => '2014-08-30', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Pogoń Szczecin', :start => '2014-08-30', :round_id => Round.last.id)
Round.create(:name => '8')
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Ruch Chorzów', :start => '2014-09-13', :round_id => Round.last.id)
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Lechia Gdańsk', :start => '2014-09-13', :round_id => Round.last.id)
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Wisła Kraków', :start => '2014-09-13', :round_id => Round.last.id)
Match.create(:teamA => 'Cracovia', :teamB => 'Górnik Łęczna', :start => '2014-09-13', :round_id => Round.last.id)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Śląsk Wrocław', :start => '2014-09-13', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Piast Gliwice', :start => '2014-09-13', :round_id => Round.last.id)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Lech Poznań', :start => '2014-09-13', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2014-09-13', :round_id => Round.last.id)
Round.create(:name => '9')
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Cracovia', :start => '2014-09-20', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Legia Warszawa', :start => '2014-09-20', :round_id => Round.last.id)
Match.create(:teamA => 'Lech Poznań', :teamB => 'Zawisza Bydgoszcz', :start => '2014-09-20', :round_id => Round.last.id)
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Pogoń Szczecin', :start => '2014-09-20', :round_id => Round.last.id)
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'GKS Bełchatów', :start => '2014-09-20', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Korona Kielce', :start => '2014-09-20', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Górnik Zabrze', :start => '2014-09-20', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Jagiellonia Białystok', :start => '2014-09-20', :round_id => Round.last.id)
Round.create(:name => '10')
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Pogoń Szczecin', :start => '2014-09-27', :round_id => Round.last.id)
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Ruch Chorzów', :start => '2014-09-27', :round_id => Round.last.id)
Match.create(:teamA => 'Cracovia', :teamB => 'Wisła Kraków', :start => '2014-09-27', :round_id => Round.last.id)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Lech Poznań', :start => '2014-09-27', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Lechia Gdańsk', :start => '2014-09-27', :round_id => Round.last.id)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2014-09-27', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Piast Gliwice', :start => '2014-09-27', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Górnik Łęczna', :start => '2014-09-27', :round_id => Round.last.id)
Round.create(:name => '11')
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Legia Warszawa', :start => '2014-10-4', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Jagiellonia Białystok', :start => '2014-10-4', :round_id => Round.last.id)
Match.create(:teamA => 'Lech Poznań', :teamB => 'GKS Bełchatów', :start => '2014-10-4', :round_id => Round.last.id)
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Cracovia', :start => '2014-10-4', :round_id => Round.last.id)
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Górnik Zabrze', :start => '2014-10-4', :round_id => Round.last.id)
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Zawisza Bydgoszcz', :start => '2014-10-4', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Śląsk Wrocław', :start => '2014-10-4', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Korona Kielce', :start => '2014-10-4', :round_id => Round.last.id)
Round.create(:name => '12')
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'GKS Bełchatów', :start => '2014-10-18', :round_id => Round.last.id)
Match.create(:teamA => 'Cracovia', :teamB => 'Ruch Chorzów', :start => '2014-10-18', :round_id => Round.last.id)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Lechia Gdańsk', :start => '2014-10-18', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Wisła Kraków', :start => '2014-10-18', :round_id => Round.last.id)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Pogoń Szczecin', :start => '2014-10-18', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Lech Poznań', :start => '2014-10-18', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Piast Gliwice', :start => '2014-10-18', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Górnik Łęczna', :start => '2014-10-18', :round_id => Round.last.id)
Round.create(:name => '13')
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Jagiellonia Białystok', :start => '2014-10-25', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2014-10-25', :round_id => Round.last.id)
Match.create(:teamA => 'Lech Poznań', :teamB => 'Górnik Łęczna', :start => '2014-10-25', :round_id => Round.last.id)
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Śląsk Wrocław', :start => '2014-10-25', :round_id => Round.last.id)
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Korona Kielce', :start => '2014-10-25', :round_id => Round.last.id)
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Cracovia', :start => '2014-10-25', :round_id => Round.last.id)
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Górnik Zabrze', :start => '2014-10-25', :round_id => Round.last.id)
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Legia Warszawa', :start => '2014-10-25', :round_id => Round.last.id)
Round.create(:name => '14')
Match.create(:teamA => 'Cracovia', :teamB => 'Zawisza Bydgoszcz', :start => '2014-11-2', :round_id => Round.last.id)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Ruch Chorzów', :start => '2014-11-2', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Pogoń Szczecin', :start => '2014-11-2', :round_id => Round.last.id)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'GKS Bełchatów', :start => '2014-11-2', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Wisła Kraków', :start => '2014-11-2', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Lech Poznań', :start => '2014-11-2', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Piast Gliwice', :start => '2014-11-2', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Lechia Gdańsk', :start => '2014-11-2', :round_id => Round.last.id)
Round.create(:name => '15')
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Górnik Łęczna', :start => '2014-11-8', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Śląsk Wrocław', :start => '2014-11-8', :round_id => Round.last.id)
Match.create(:teamA => 'Lech Poznań', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2014-11-8', :round_id => Round.last.id)
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Korona Kielce', :start => '2014-11-8', :round_id => Round.last.id)
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Legia Warszawa', :start => '2014-11-8', :round_id => Round.last.id)
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Cracovia', :start => '2014-11-8', :round_id => Round.last.id)
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Górnik Zabrze', :start => '2014-11-8', :round_id => Round.last.id)
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Jagiellonia Białystok', :start => '2014-11-8', :round_id => Round.last.id)
Round.create(:name => '16')
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Lech Poznań', :start => '2014-11-22', :round_id => Round.last.id)
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Legia Warszawa', :start => '2014-11-22', :round_id => Round.last.id)
Match.create(:teamA => 'Cracovia', :teamB => 'Górnik Zabrze', :start => '2014-11-22', :round_id => Round.last.id)
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Jagiellonia Białystok', :start => '2014-11-22', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Zawisza Bydgoszcz', :start => '2014-11-22', :round_id => Round.last.id)
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Śląsk Wrocław', :start => '2014-11-22', :round_id => Round.last.id)
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2014-11-22', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Górnik Łęczna', :start => '2014-11-22', :round_id => Round.last.id)
Round.create(:name => '17')
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Wisła Kraków', :start => '2014-11-29', :round_id => Round.last.id)
Match.create(:teamA => 'Lech Poznań', :teamB => 'Górnik Zabrze', :start => '2014-11-29', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Lechia Gdańsk', :start => '2014-11-29', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Ruch Chorzów', :start => '2014-11-29', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Pogoń Szczecin', :start => '2014-11-29', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'GKS Bełchatów', :start => '2014-11-29', :round_id => Round.last.id)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Zawisza Bydgoszcz', :start => '2014-11-29', :round_id => Round.last.id)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Cracovia', :start => '2014-11-29', :round_id => Round.last.id)
Round.create(:name => '18')
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Piast Gliwice', :start => '2014-12-6', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Lech Poznań', :start => '2014-12-6', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Legia Warszawa', :start => '2014-12-6', :round_id => Round.last.id)
Match.create(:teamA => 'Cracovia', :teamB => 'Jagiellonia Białystok', :start => '2014-12-6', :round_id => Round.last.id)
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Korona Kielce', :start => '2014-12-6', :round_id => Round.last.id)
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Śląsk Wrocław', :start => '2014-12-6', :round_id => Round.last.id)
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2014-12-6', :round_id => Round.last.id)
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Górnik Łęczna', :start => '2014-12-6', :round_id => Round.last.id)
Round.create(:name => '19')
Match.create(:teamA => 'Lech Poznań', :teamB => 'Lechia Gdańsk', :start => '2014-12-13', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Ruch Chorzów', :start => '2014-12-13', :round_id => Round.last.id)
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Pogoń Szczecin', :start => '2014-12-13', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'GKS Bełchatów', :start => '2014-12-13', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Zawisza Bydgoszcz', :start => '2014-12-13', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Cracovia', :start => '2014-12-13', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Legia Warszawa', :start => '2014-12-13', :round_id => Round.last.id)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Górnik Zabrze', :start => '2014-12-13', :round_id => Round.last.id)
Round.create(:name => '20')
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Piast Gliwice', :start => '2015-02-14', :round_id => Round.last.id)
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Wisła Kraków', :start => '2015-02-14', :round_id => Round.last.id)
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Lech Poznań', :start => '2015-02-14', :round_id => Round.last.id)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Jagiellonia Białystok', :start => '2015-02-14', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Korona Kielce', :start => '2015-02-14', :round_id => Round.last.id)
Match.create(:teamA => 'Cracovia', :teamB => 'Śląsk Wrocław', :start => '2015-02-14', :round_id => Round.last.id)
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2015-02-14', :round_id => Round.last.id)
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Górnik Łęczna', :start => '2015-02-14', :round_id => Round.last.id)
Round.create(:name => '21')
Match.create(:teamA => 'Lech Poznań', :teamB => 'Ruch Chorzów', :start => '2015-02-21', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Pogoń Szczecin', :start => '2015-02-21', :round_id => Round.last.id)
Match.create(:teamA => 'Piast Gliwice', :teamB => 'GKS Bełchatów', :start => '2015-02-21', :round_id => Round.last.id)
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Zawisza Bydgoszcz', :start => '2015-02-21', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Cracovia', :start => '2015-02-21', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Legia Warszawa', :start => '2015-02-21', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Górnik Zabrze', :start => '2015-02-21', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Jagiellonia Białystok', :start => '2015-02-21', :round_id => Round.last.id)
Round.create(:name => '22')
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Piast Gliwice', :start => '2015-2-28', :round_id => Round.last.id)
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Wisła Kraków', :start => '2015-2-28', :round_id => Round.last.id)
Match.create(:teamA => 'Cracovia', :teamB => 'Lech Poznań', :start => '2015-2-28', :round_id => Round.last.id)
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Lechia Gdańsk', :start => '2015-2-28', :round_id => Round.last.id)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Korona Kielce', :start => '2015-2-28', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Śląsk Wrocław', :start => '2015-2-28', :round_id => Round.last.id)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2015-2-28', :round_id => Round.last.id)
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Górnik Łęczna', :start => '2015-2-28', :round_id => Round.last.id)
Round.create(:name => '23')
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Pogoń Szczecin', :start => '2015-03-7', :round_id => Round.last.id)
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'GKS Bełchatów', :start => '2015-03-7', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Zawisza Bydgoszcz', :start => '2015-03-7', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Cracovia', :start => '2015-03-7', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Legia Warszawa', :start => '2015-03-7', :round_id => Round.last.id)
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Górnik Zabrze', :start => '2015-03-7', :round_id => Round.last.id)
Match.create(:teamA => 'Lech Poznań', :teamB => 'Jagiellonia Białystok', :start => '2015-03-7', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Korona Kielce', :start => '2015-03-7', :round_id => Round.last.id)
Round.create(:name => '24')
Match.create(:teamA => 'Cracovia', :teamB => 'Piast Gliwice', :start => '2015-03-14', :round_id => Round.last.id)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Wisła Kraków', :start => '2015-03-14', :round_id => Round.last.id)
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Lech Poznań', :start => '2015-03-14', :round_id => Round.last.id)
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Lechia Gdańsk', :start => '2015-03-14', :round_id => Round.last.id)
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Ruch Chorzów', :start => '2015-03-14', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Śląsk Wrocław', :start => '2015-03-14', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2015-03-14', :round_id => Round.last.id)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Górnik Łęczna', :start => '2015-03-14', :round_id => Round.last.id)
Round.create(:name => '25')
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'GKS Bełchatów', :start => '2015-03-21', :round_id => Round.last.id)
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Zawisza Bydgoszcz', :start => '2015-03-21', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Cracovia', :start => '2015-03-21', :round_id => Round.last.id)
Match.create(:teamA => 'Lech Poznań', :teamB => 'Legia Warszawa', :start => '2015-03-21', :round_id => Round.last.id)
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Górnik Zabrze', :start => '2015-03-21', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Jagiellonia Białystok', :start => '2015-03-21', :round_id => Round.last.id)
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Korona Kielce', :start => '2015-03-21', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Śląsk Wrocław', :start => '2015-03-21', :round_id => Round.last.id)
Round.create(:name => '26')
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Piast Gliwice', :start => '2015-04-4', :round_id => Round.last.id)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Wisła Kraków', :start => '2015-04-4', :round_id => Round.last.id)
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Lech Poznań', :start => '2015-04-4', :round_id => Round.last.id)
Match.create(:teamA => 'Cracovia', :teamB => 'Lechia Gdańsk', :start => '2015-04-4', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Ruch Chorzów', :start => '2015-04-4', :round_id => Round.last.id)
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Pogoń Szczecin', :start => '2015-04-4', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2015-04-4', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Górnik Łęczna', :start => '2015-04-4', :round_id => Round.last.id)
Round.create(:name => '27')
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Zawisza Bydgoszcz', :start => '2015-04-11', :round_id => Round.last.id)
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Cracovia', :start => '2015-04-11', :round_id => Round.last.id)
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Legia Warszawa', :start => '2015-04-11', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Górnik Zabrze', :start => '2015-04-11', :round_id => Round.last.id)
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Jagiellonia Białystok', :start => '2015-04-11', :round_id => Round.last.id)
Match.create(:teamA => 'Lech Poznań', :teamB => 'Korona Kielce', :start => '2015-04-11', :round_id => Round.last.id)
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Śląsk Wrocław', :start => '2015-04-11', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2015-04-11', :round_id => Round.last.id)
Round.create(:name => '28')
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Piast Gliwice', :start => '2015-04-18', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Wisła Kraków', :start => '2015-04-18', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Lech Poznań', :start => '2015-04-18', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Lechia Gdańsk', :start => '2015-04-18', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Ruch Chorzów', :start => '2015-04-18', :round_id => Round.last.id)
Match.create(:teamA => 'Cracovia', :teamB => 'Pogoń Szczecin', :start => '2015-04-18', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'GKS Bełchatów', :start => '2015-04-18', :round_id => Round.last.id)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Zawisza Bydgoszcz', :start => '2015-04-18', :round_id => Round.last.id)
Round.create(:name => '29')
Match.create(:teamA => 'Zawisza Bydgoszcz', :teamB => 'Cracovia', :start => '2015-04-25', :round_id => Round.last.id)
Match.create(:teamA => 'Ruch Chorzów', :teamB => 'Legia Warszawa', :start => '2015-04-25', :round_id => Round.last.id)
Match.create(:teamA => 'Pogoń Szczecin', :teamB => 'Górnik Zabrze', :start => '2015-04-25', :round_id => Round.last.id)
Match.create(:teamA => 'GKS Bełchatów', :teamB => 'Jagiellonia Białystok', :start => '2015-04-25', :round_id => Round.last.id)
Match.create(:teamA => 'Wisła Kraków', :teamB => 'Korona Kielce', :start => '2015-04-25', :round_id => Round.last.id)
Match.create(:teamA => 'Lech Poznań', :teamB => 'Śląsk Wrocław', :start => '2015-04-25', :round_id => Round.last.id)
Match.create(:teamA => 'Piast Gliwice', :teamB => 'Podbeskidzie Bielsko-Biała', :start => '2015-04-25', :round_id => Round.last.id)
Match.create(:teamA => 'Lechia Gdańsk', :teamB => 'Górnik Łęczna', :start => '2015-04-25', :round_id => Round.last.id)
Round.create(:name => '30')
Match.create(:teamA => 'Górnik Łęczna', :teamB => 'Piast Gliwice', :start => '2015-04-29', :round_id => Round.last.id)
Match.create(:teamA => 'Śląsk Wrocław', :teamB => 'Wisła Kraków', :start => '2015-04-29', :round_id => Round.last.id)
Match.create(:teamA => 'Podbeskidzie Bielsko-Biała', :teamB => 'Lech Poznań', :start => '2015-04-29', :round_id => Round.last.id)
Match.create(:teamA => 'Korona Kielce', :teamB => 'Lechia Gdańsk', :start => '2015-04-29', :round_id => Round.last.id)
Match.create(:teamA => 'Legia Warszawa', :teamB => 'Pogoń Szczecin', :start => '2015-04-29', :round_id => Round.last.id)
Match.create(:teamA => 'Cracovia', :teamB => 'GKS Bełchatów', :start => '2015-04-29', :round_id => Round.last.id)
Match.create(:teamA => 'Górnik Zabrze', :teamB => 'Zawisza Bydgoszcz', :start => '2015-04-29', :round_id => Round.last.id)
Match.create(:teamA => 'Jagiellonia Białystok', :teamB => 'Ruch Chorzów', :start => '2015-04-29', :round_id => Round.last.id)
